    name: fluent-ui-icons-db
    
    on:
      workflow_dispatch:
      schedule:
        - cron: "0 0 * * 6"                                   # runs at 00:00 UTC every sunday
    
    jobs:
      fluent-ui-icons-indexer:
        runs-on: ubuntu-latest
    
        steps:
          - name: checkout repo content                         # checkout the repository content to github runner.
            uses: actions/checkout@v2                         
            
          - name: setup node                                    # install node
            uses: actions/setup-node@v2                         
            with:
              node-version: '14'

          - name: setup python                                  # install python
            uses: actions/setup-python@v2
            with:
              python-version: '3.8'                             

          - name: index icons                                   # run icon indexer python script
            run: |
              python indexer.py --production
              
          - name: install dependecies                           # install dependecies
            run: npm install
            
          - name: build website                                 # build website
            run: npm run build:web

          - uses: stefanzweifel/git-auto-commit-action@v4       # commit changes (if available)
            with:
              commit_message: 'chore: updated icons database'
              commit_user_name: Benny Bot
              commit_user_email: bennymegk@gmail.com
              commit_author: bennymeg <bennymegk@gmail.com>
              
          - uses: gautamkrishnar/keepalive-workflow@v1
            with:
                committer_username: Benny Bot
                committer_email: bennymegk@gmail.com
