    name: fluent-ui-icons-db
    
    on:
      workflow_dispatch:
      schedule:
        - cron: "0 0 * * 0"                                     # runs at 12:00AM UTC every Sunday
    
    jobs:
      fluent-ui-icons-indexer:
        runs-on: ubuntu-latest
    
        steps:
          - name: checkout repo content                         # checkout the repository content to github runner.
            uses: actions/checkout@v3                         
            
          - name: setup node                                    # install node
            uses: actions/setup-node@v2                         
            with:
              node-version: '18'

          - name: setup python                                  # install python
            uses: actions/setup-python@v2
            with:
              python-version: '3.9'                             

          - name: install dependencies                          # install dependencies
            run: npm install --force

          - name: update fluent ui icons dependency             # install latest fluent ui dependency
            run: npm install -D @fluentui/svg-icons@latest --force

          - name: index icons                                   # run icon indexer python script
            run: |
              python indexer.py --production
            
          - name: build website                                 # build website
            run: npm run build:web

          - name: commit changes                                # commit changes (if available)
            uses: stefanzweifel/git-auto-commit-action@v4       
            with:
              commit_message: 'chore: updated icons database'
              commit_user_name: Benny Bot
              commit_user_email: bennymegk@gmail.com
              commit_author: bennymeg <bennymegk@gmail.com>
              
          - name: assert workflow active                        # keep workflow alive (if needed)
            uses: gautamkrishnar/keepalive-workflow@v1
            with:
                committer_username: Benny Bot
                committer_email: bennymegk@gmail.com
